# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 19:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvone', '0004_auto_20170605_2014'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
